%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Git\bleedinglevel\logs\log_refactored.csv
%
% Auto-generated by MATLAB on 09-May-2019 13:32:45

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "Grams", "BloodAccumulated", "WaterAccumulated", "Delta", "DeltaofDelta"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Git\bleedinglevel\logs\log_refactored.csv", opts);

%% Convert to output type
Time = tbl.Time;
Grams = tbl.Grams;
BloodAccumulated = tbl.BloodAccumulated;
WaterAccumulated = tbl.WaterAccumulated;
Delta = tbl.Delta;
DeltaofDelta = tbl.DeltaofDelta;

%% Clear temporary variables
clear opts tbl